project:
  type: website

website:
  title: "ParadigmDataGroup, LLC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - listings.qmd

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true
    dpi: 320
    fig-format: retina
    fig-asp: 0.618



